### PR TITLE
fixed: check user is not logged in before adding unsubscribe link in …

### LINKED ISSUE #169: Public event email unsubscribe link is not working for logged in users
**Elgg version**
Elgg v4.1

**Plugin version**
Event manager v13.0.2

**Plugin source**
Composer installation

**Describe the bug**
Public event email unsubscribe link is not working for logged in users

**To Reproduce**
1. Create a public event in a public group (in the registration section, enable "Allow not-loggedin users to register?")
2. Attend to this event
3. Receive the "Event registration confirmation" email
4. In the email, click on the "If you no longer wish to attend the event" link
5. The event unsubscribe page is displayed
6. Click Submit button (without changing the email address)
7. See "No registration could be found for the supplied e-mail address" error

**Expected behavior**
This unsubscribe link should not be displayed in "Event registration confirmation" email if user is logged in. This link is intend to external users.

### PR DESCRIPTION
**Pull request by oseg**
…email

Fix #169

### CODE REVIEW

File: classes/Event.php [hunk 1]
```diff
@@ -542,7 +542,7 @@ protected function notifyOnRsvp(string $type, int $to = null): void {
 					}
 				}
 	
-				if ($this->register_nologin) {
+				if ($this->register_nologin && !elgg_is_logged_in()) {
```
Comment (jdalsem) [inline classes/Event.php:545]: can you change this to `$to_entity instanceof \EventRegistration` as that will make sure this function works always as expected (even if used logged out or logged in)

**Review by jdalsem — CHANGES_REQUESTED** [review]

File: classes/Event.php (hunk 1 above)
Comment (oseg) [reply classes/Event.php]: You are right, that's a better implementation: done

Comment (jdalsem) [reply classes/Event.php]: Thanks for updating... it would help next time to squash your commits (if they apply to the same change). Commit messages will end up in the release notes. If makes no sense to have 2 messages related to the same change. I have squashed the commits for you this time.

Comment (oseg) [reply classes/Event.php]: ok, I will do it next time
